name: Continuos Deployment workflow

on:
  push:
    branches:
      - main

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  IMAGE_NAME: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Heroku login
        run: heroku container:login
      - name: Build Docker Image
        run: docker build -t ${{env.IMAGE_NAME}} .
      - name: Push Docker Image
        run: heroku container:push web --app js-heroku-front-demon
      - name: Release
        run: heroku container:release web --app js-heroku-front-demon
   
